name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build for macOS
      run: swift build -v
    - name: Run macOS tests
      run: swift test -v
    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme NetworkLayer -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
    - name: Run iOS tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme NetworkLayer -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
